### ISSUE TITLE
ur dumb

### ISSUE THREAD

**Issue by ralsei** [mustardsandwich/mustardsandwich.github.io#1]
heheeeeeeeeeeeeeeeeeeeeEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE
E
E
EE
E
E

**Comment by mustardsandwich** [comment]
So I looked into this and I think I've discovered the root of the problem. It seems that at some point in time, I was born, and here we are. I might revisit this issue in the future.
